--小弓庙--
--渔船加宜居
INSERT INTO ImprovementModifiers (ImprovementType, ModifierID) VALUES
('IMPROVEMENT_FISHING_BOATS', 'TEMPLE_ARTEMIS_FISHING_BOATS_AMENITY_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('TEMPLE_ARTEMIS_FISHING_BOATS_AMENITY_Cos' , 'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_AMENITY', 'TEMPLE_ARTEMIS_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('TEMPLE_ARTEMIS_FISHING_BOATS_AMENITY_Cos' , 'Amount', '1');
--南极站--
--雪地加2科1锤
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_AMUNDSEN_SCOTT_RESEARCH_STATION', 'AMUNDSEN_SNOW_SCIENCE_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('AMUNDSEN_SNOW_SCIENCE_Cos' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'SNOW_REQUIREMENTS_Cos');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('AMUNDSEN_SNOW_SCIENCE_Cos' , 'YieldType', 'YIELD_SCIENCE'),
('AMUNDSEN_SNOW_SCIENCE_Cos' , 'Amount', '2');
INSERT INTO RequirementSets (RequirementSetId , RequirementSetType)
	VALUES ('SNOW_REQUIREMENTS_Cos' , 'REQUIREMENTSET_TEST_ANY');
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId) VALUES
('SNOW_REQUIREMENTS_Cos' , 'REQUIRES_PLOT_HAS_SNOW'),
('SNOW_REQUIREMENTS_Cos' , 'PLOT_IS_SNOW_HILLS_TERRAIN_REQUIREMENT');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_AMUNDSEN_SCOTT_RESEARCH_STATION', 'AMUNDSEN_SNOW_PRODUCTION_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('AMUNDSEN_SNOW_PRODUCTION_Cos' , 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'SNOW_REQUIREMENTS_Cos');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('AMUNDSEN_SNOW_PRODUCTION_Cos' , 'YieldType', 'YIELD_PRODUCTION'),
('AMUNDSEN_SNOW_PRODUCTION_Cos' , 'Amount', '1');
--埃菲尔铁塔--
--全境+2金
UPDATE Buildings SET RegionalRange=100000 WHERE BuildingType='BUILDING_EIFFEL_TOWER';
INSERT INTO Building_YieldChanges (BuildingType, YieldType, YieldChange) VALUES
('BUILDING_EIFFEL_TOWER', 'YIELD_GOLD', 2);
--迷人市中心、社区、保护区+1文化，惊艳+3
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_EIFFEL_TOWER', 'EIFFEL_2_CITY_CENTER_Cos'),
('BUILDING_EIFFEL_TOWER', 'EIFFEL_4_CITY_CENTER_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
('EIFFEL_2_CITY_CENTER_Cos', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL'),
('EIFFEL_4_CITY_CENTER_Cos', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('EIFFEL_2_CITY_CENTER_Cos', 'RequiredAppeal', 2),
('EIFFEL_2_CITY_CENTER_Cos', 'Description', 'LOC_DISTRICT_APPEAL_CULTURE'),
('EIFFEL_2_CITY_CENTER_Cos', 'DistrictType', 'DISTRICT_CITY_CENTER'),
('EIFFEL_2_CITY_CENTER_Cos', 'YieldChange', 1),
('EIFFEL_2_CITY_CENTER_Cos', 'YieldType', 'YIELD_CULTURE'),
('EIFFEL_4_CITY_CENTER_Cos', 'RequiredAppeal', 4),
('EIFFEL_4_CITY_CENTER_Cos', 'Description', 'LOC_DISTRICT_APPEAL_CULTURE'),
('EIFFEL_4_CITY_CENTER_Cos', 'DistrictType', 'DISTRICT_CITY_CENTER'),
('EIFFEL_4_CITY_CENTER_Cos', 'YieldChange', 2),
('EIFFEL_4_CITY_CENTER_Cos', 'YieldType', 'YIELD_CULTURE');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_EIFFEL_TOWER', 'EIFFEL_2_NEIGHBORHOOD_Cos'),
('BUILDING_EIFFEL_TOWER', 'EIFFEL_4_NEIGHBORHOOD_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
('EIFFEL_2_NEIGHBORHOOD_Cos', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL'),
('EIFFEL_4_NEIGHBORHOOD_Cos', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('EIFFEL_2_NEIGHBORHOOD_Cos', 'RequiredAppeal', 2),
('EIFFEL_2_NEIGHBORHOOD_Cos', 'Description', 'LOC_DISTRICT_APPEAL_CULTURE'),
('EIFFEL_2_NEIGHBORHOOD_Cos', 'DistrictType', 'DISTRICT_NEIGHBORHOOD'),
('EIFFEL_2_NEIGHBORHOOD_Cos', 'YieldChange', 1),
('EIFFEL_2_NEIGHBORHOOD_Cos', 'YieldType', 'YIELD_CULTURE'),
('EIFFEL_4_NEIGHBORHOOD_Cos', 'RequiredAppeal', 4),
('EIFFEL_4_NEIGHBORHOOD_Cos', 'Description', 'LOC_DISTRICT_APPEAL_CULTURE'),
('EIFFEL_4_NEIGHBORHOOD_Cos', 'DistrictType', 'DISTRICT_NEIGHBORHOOD'),
('EIFFEL_4_NEIGHBORHOOD_Cos', 'YieldChange', 2),
('EIFFEL_4_NEIGHBORHOOD_Cos', 'YieldType', 'YIELD_CULTURE');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_EIFFEL_TOWER', 'EIFFEL_2_PRESERVE_Cos'),
('BUILDING_EIFFEL_TOWER', 'EIFFEL_4_PRESERVE_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType) VALUES
('EIFFEL_2_PRESERVE_Cos', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL'),
('EIFFEL_4_PRESERVE_Cos', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_APPEAL');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('EIFFEL_2_PRESERVE_Cos', 'RequiredAppeal', 2),
('EIFFEL_2_PRESERVE_Cos', 'Description', 'LOC_DISTRICT_APPEAL_CULTURE'),
('EIFFEL_2_PRESERVE_Cos', 'DistrictType', 'DISTRICT_PRESERVE'),
('EIFFEL_2_PRESERVE_Cos', 'YieldChange', 1),
('EIFFEL_2_PRESERVE_Cos', 'YieldType', 'YIELD_CULTURE'),
('EIFFEL_4_PRESERVE_Cos', 'RequiredAppeal', 4),
('EIFFEL_4_PRESERVE_Cos', 'Description', 'LOC_DISTRICT_APPEAL_CULTURE'),
('EIFFEL_4_PRESERVE_Cos', 'DistrictType', 'DISTRICT_PRESERVE'),
('EIFFEL_4_PRESERVE_Cos', 'YieldChange', 2),
('EIFFEL_4_PRESERVE_Cos', 'YieldType', 'YIELD_CULTURE');
--惊艳+1文
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_EIFFEL_TOWER', 'EIFFEL_BREATHTAKING_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('EIFFEL_BREATHTAKING_Cos', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_BREATHTAKING_APPEAL');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('EIFFEL_BREATHTAKING_Cos', 'YieldType', 'YIELD_CULTURE'),
('EIFFEL_BREATHTAKING_Cos', 'Amount', '1');
--烂地庙--
--加一锤
INSERT INTO Building_YieldChanges (BuildingType, YieldType, YieldChange) VALUES
('BUILDING_ETEMENANKI', 'YIELD_PRODUCTION', 1);
--冬宫--
--本城艺术巨作文化和旅游业绩翻三倍
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_HERMITAGE', 'HERMITAGE_SCULPTURE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('HERMITAGE_SCULPTURE_Cos', 'MODIFIER_SINGLE_CITY_ADJUST_GREATWORK_YIELD', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('HERMITAGE_SCULPTURE_Cos', 'GreatWorkObjectType', 'GREATWORKOBJECT_SCULPTURE'),
('HERMITAGE_SCULPTURE_Cos', 'YieldType', 'YIELD_CULTURE'),
('HERMITAGE_SCULPTURE_Cos', 'ScalingFactor', '300');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_HERMITAGE', 'HERMITAGE_PORTRAIT_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('HERMITAGE_PORTRAIT_Cos', 'MODIFIER_SINGLE_CITY_ADJUST_GREATWORK_YIELD', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('HERMITAGE_PORTRAIT_Cos', 'GreatWorkObjectType', 'GREATWORKOBJECT_PORTRAIT'),
('HERMITAGE_PORTRAIT_Cos', 'YieldType', 'YIELD_CULTURE'),
('HERMITAGE_PORTRAIT_Cos', 'ScalingFactor', '300');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_HERMITAGE', 'HERMITAGE_LANDSCAPE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('HERMITAGE_LANDSCAPE_Cos', 'MODIFIER_SINGLE_CITY_ADJUST_GREATWORK_YIELD', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('HERMITAGE_LANDSCAPE_Cos', 'GreatWorkObjectType', 'GREATWORKOBJECT_LANDSCAPE'),
('HERMITAGE_LANDSCAPE_Cos', 'YieldType', 'YIELD_CULTURE'),
('HERMITAGE_LANDSCAPE_Cos', 'ScalingFactor', '300');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_HERMITAGE', 'HERMITAGE_RELIGIOUS_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('HERMITAGE_RELIGIOUS_Cos', 'MODIFIER_SINGLE_CITY_ADJUST_GREATWORK_YIELD', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('HERMITAGE_RELIGIOUS_Cos', 'GreatWorkObjectType', 'GREATWORKOBJECT_RELIGIOUS'),
('HERMITAGE_RELIGIOUS_Cos', 'YieldType', 'YIELD_CULTURE'),
('HERMITAGE_RELIGIOUS_Cos', 'ScalingFactor', '300');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_HERMITAGE', 'HERMITAGE_SCULPTURE_TOURISM_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('HERMITAGE_SCULPTURE_TOURISM_Cos', 'MODIFIER_SINGLE_CITY_ADJUST_TOURISM', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('HERMITAGE_SCULPTURE_TOURISM_Cos', 'GreatWorkObjectType', 'GREATWORKOBJECT_SCULPTURE'),
('HERMITAGE_SCULPTURE_TOURISM_Cos', 'ScalingFactor', '300');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_HERMITAGE', 'HERMITAGE_PORTRAIT_TOURISM_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('HERMITAGE_PORTRAIT_TOURISM_Cos', 'MODIFIER_SINGLE_CITY_ADJUST_TOURISM', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('HERMITAGE_PORTRAIT_TOURISM_Cos', 'GreatWorkObjectType', 'GREATWORKOBJECT_PORTRAIT'),
('HERMITAGE_PORTRAIT_TOURISM_Cos', 'ScalingFactor', '300');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_HERMITAGE', 'HERMITAGE_LANDSCAPE_TOURISM_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('HERMITAGE_LANDSCAPE_TOURISM_Cos', 'MODIFIER_SINGLE_CITY_ADJUST_TOURISM', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('HERMITAGE_LANDSCAPE_TOURISM_Cos', 'GreatWorkObjectType', 'GREATWORKOBJECT_LANDSCAPE'),
('HERMITAGE_LANDSCAPE_TOURISM_Cos', 'ScalingFactor', '300');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_HERMITAGE', 'HERMITAGE_RELIGIOUS_TOURISM_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('HERMITAGE_RELIGIOUS_TOURISM_Cos', 'MODIFIER_SINGLE_CITY_ADJUST_TOURISM', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('HERMITAGE_RELIGIOUS_TOURISM_Cos', 'GreatWorkObjectType', 'GREATWORKOBJECT_RELIGIOUS'),
('HERMITAGE_RELIGIOUS_TOURISM_Cos', 'ScalingFactor', '300');
--巴拿马--
--运河相邻锤
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_PANAMA_CANAL', 'PANAMA_CANAL_PRODUCTION_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('PANAMA_CANAL_PRODUCTION_Cos', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS', 'DISTRICT_IS_CANAL');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('PANAMA_CANAL_PRODUCTION_Cos', 'YieldTypeToMirror', 'YIELD_GOLD'),
('PANAMA_CANAL_PRODUCTION_Cos', 'YieldTypeToGrant', 'YIELD_PRODUCTION');
--运河加速100%
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_PANAMA_CANAL', 'PANAMA_CANAL_BOOST_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType , SubjectRequirementSetId) VALUES
('PANAMA_CANAL_BOOST_Cos', 'MODIFIER_PLAYER_CITIES_ADJUST_DISTRICT_PRODUCTION', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('PANAMA_CANAL_BOOST_Cos', 'DistrictType', 'DISTRICT_CANAL'),
('PANAMA_CANAL_BOOST_Cos', 'Amount', '100');
--百老汇--
--剧院相邻给旅游业绩
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_BROADWAY', 'BROADWAY_CULTURE_TOURISM_DISTRICTS_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType , SubjectRequirementSetId) VALUES
('BROADWAY_CULTURE_TOURISM_DISTRICTS_Cos', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_TOURISM_ADJACENCY_YIELD_MOFIFIER', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('BROADWAY_CULTURE_TOURISM_DISTRICTS_Cos', 'YieldType', 'YIELD_CULTURE'),
('BROADWAY_CULTURE_TOURISM_DISTRICTS_Cos', 'Amount', '100');
--剧院相邻给金币
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_BROADWAY', 'BROADWAY_THEATER_GOLD_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('BROADWAY_THEATER_GOLD_Cos', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS', 'DISTRICT_IS_THEATER');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('BROADWAY_THEATER_GOLD_Cos', 'YieldTypeToMirror', 'YIELD_CULTURE'),
('BROADWAY_THEATER_GOLD_Cos', 'YieldTypeToGrant', 'YIELD_GOLD');
--贝伦塔--
--所有城市送建筑
UPDATE Modifiers SET SubjectRequirementSetId=NULL WHERE ModifierId='TORREDEBELEM_CHEAPEST_BUILDING';
--+1商路容量
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_TORRE_DE_BELEM', 'BELEM_ADDTRADEROUTE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('BELEM_ADDTRADEROUTE_Cos', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_CAPACITY', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('BELEM_ADDTRADEROUTE_Cos', 'Amount', '1');
--兵马俑--
--任何平地都可造
INSERT INTO Building_ValidTerrains (BuildingType, TerrainType) VALUES
('BUILDING_TERRACOTTA_ARMY', 'TERRAIN_TUNDRA'),
('BUILDING_TERRACOTTA_ARMY', 'TERRAIN_SNOW'),
('BUILDING_TERRACOTTA_ARMY', 'TERRAIN_DESERT');
--铁山--
--战略储量+20
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_JEBEL_BARKAL', 'JEBEL_BARKAL_ADJUST_RESOURCE_STOCKPILE_CAP_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('JEBEL_BARKAL_ADJUST_RESOURCE_STOCKPILE_CAP_Cos', 'MODIFIER_PLAYER_ADJUST_RESOURCE_STOCKPILE_CAP', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('JEBEL_BARKAL_ADJUST_RESOURCE_STOCKPILE_CAP_Cos', 'Amount', '20');
--布达拉宫--
--人口上山
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_POTALA_PALACE', 'TRAIT_WORK_GRASS_MOUNTAIN'),
('BUILDING_POTALA_PALACE', 'TRAIT_WORK_PLAINS_MOUNTAIN'),
('BUILDING_POTALA_PALACE', 'TRAIT_WORK_DESERT_MOUNTAIN'),
('BUILDING_POTALA_PALACE', 'TRAIT_WORK_TUNDRA_MOUNTAIN'),
('BUILDING_POTALA_PALACE', 'TRAIT_WORK_SNOW_MOUNTAIN');
--山脉+1信仰1粮
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_POTALA_PALACE', 'POTALA_PALACE_MOUNTAIN_FAITH_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('POTALA_PALACE_MOUNTAIN_FAITH_Cos', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'REQUIREMENTS_PLOT_IS_MOUNTAIN');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('POTALA_PALACE_MOUNTAIN_FAITH_Cos', 'YieldType', 'YIELD_FAITH'),
('POTALA_PALACE_MOUNTAIN_FAITH_Cos', 'Amount', '1');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_POTALA_PALACE', 'POTALA_PALACE_MOUNTAIN_FOOD_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('POTALA_PALACE_MOUNTAIN_FOOD_Cos', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'REQUIREMENTS_PLOT_IS_MOUNTAIN');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('POTALA_PALACE_MOUNTAIN_FOOD_Cos', 'YieldType', 'YIELD_FOOD'),
('POTALA_PALACE_MOUNTAIN_FOOD_Cos', 'Amount', '1');
--大灯塔--
--送海统
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_GREAT_LIGHTHOUSE', 'GREAT_LIGHTHOUSE_GRANT_ADMIRAL_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType , SubjectRequirementSetId , RunOnce , Permanent) VALUES
('GREAT_LIGHTHOUSE_GRANT_ADMIRAL_Cos', 'MODIFIER_SINGLE_CITY_GRANT_GREAT_PERSON_CLASS_IN_CITY', NULL, 1, 1);	
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES ('GREAT_LIGHTHOUSE_GRANT_ADMIRAL_Cos', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_ADMIRAL'),
('GREAT_LIGHTHOUSE_GRANT_ADMIRAL_Cos', 'Amount', '1');
--大津巴布韦-
--不需要相邻牛
UPDATE Buildings SET AdjacentResource=NULL WHERE BuildingType='BUILDING_GREAT_ZIMBABWE';
--大浴场--
--泛滥+1信仰
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_GREAT_BATH', 'GREAT_BATH_FLOODPLAINS_FAITH_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('GREAT_BATH_FLOODPLAINS_FAITH_Cos', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 'PLOT_IS_FLOODPLAINS_SAHARA');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('GREAT_BATH_FLOODPLAINS_FAITH_Cos', 'YieldType', 'YIELD_FAITH'),
('GREAT_BATH_FLOODPLAINS_FAITH_Cos', 'Amount', '1');
--基础+1信仰
INSERT INTO Building_YieldChanges (BuildingType, YieldType, YieldChange) VALUES
('BUILDING_GREAT_BATH', 'YIELD_FAITH', 1);
--高德院--
--武僧+1移动力
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_KOTOKU_IN', 'KOTOKU_IN_MONK_MOVEMENT_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('KOTOKU_IN_MONK_MOVEMENT_Cos', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT', 'UNIT_IS_MONK_Cos');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('KOTOKU_IN_MONK_MOVEMENT_Cos', 'Amount', '1');
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId)
	VALUES ('UNIT_IS_MONK_Cos' , 'REQUIRES_UNIT_IS_MONK_Cos');
INSERT INTO RequirementSets (RequirementSetId , RequirementSetType)
	VALUES ('UNIT_IS_MONK_Cos' , 'REQUIREMENTSET_TEST_ALL');
INSERT INTO Requirements (RequirementId , RequirementType)
	VALUES ('REQUIRES_UNIT_IS_MONK_Cos' , 'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES');
INSERT INTO RequirementArguments (RequirementId , Name , Value)
	VALUES ('REQUIRES_UNIT_IS_MONK_Cos' , 'UnitPromotionClass' , 'PROMOTION_CLASS_MONK');
--武僧+1劳动力
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_KOTOKU_IN', 'KOTOKU_IN_MONK_BUILDER_CHARGE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('KOTOKU_IN_MONK_BUILDER_CHARGE_Cos', 'MODIFIER_PLAYER_UNITS_ADJUST_BUILDER_CHARGES', 'UNIT_IS_MONK_Cos');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('KOTOKU_IN_MONK_BUILDER_CHARGE_Cos', 'Amount', '1');
--金门大桥--
--三环修路
UPDATE ModifierArguments SET Value='3' WHERE ModifierId='GOLDENGATE_GRANT_ROUTES' AND Name='Radius';
--通向该城国内贸易路线+8金
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_GOLDEN_GATE_BRIDGE', 'GOLDEN_GATE_TRADE_ROUTE_GOLD_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('GOLDEN_GATE_TRADE_ROUTE_GOLD_Cos', 'MODIFIER_SINGLE_CITY_ADJUST_TRADE_ROUTE_YIELD_TO_OTHERS', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('GOLDEN_GATE_TRADE_ROUTE_GOLD_Cos', 'YieldType', 'YIELD_GOLD'),
('GOLDEN_GATE_TRADE_ROUTE_GOLD_Cos', 'Amount', '8'),
('GOLDEN_GATE_TRADE_ROUTE_GOLD_Cos', 'Domestic', '1');
--建造者开拓者+1速
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_GOLDEN_GATE_BRIDGE', 'GOLDEN_GATE_FASTER_BUILDERS_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId)
	VALUES ('GOLDEN_GATE_FASTER_BUILDERS_Cos', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT','UNIT_IS_BUILDER');
INSERT INTO ModifierArguments (ModifierId , Name , Value)
	VALUES ('GOLDEN_GATE_FASTER_BUILDERS_Cos', 'Amount', '1');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_GOLDEN_GATE_BRIDGE', 'GOLDEN_GATE_FASTER_SETTLERS_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType, SubjectRequirementSetId)
	VALUES ('GOLDEN_GATE_FASTER_SETTLERS_Cos', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT','UNIT_IS_SETTLER_Cos');
INSERT INTO ModifierArguments (ModifierId , Name , Value)
	VALUES ('GOLDEN_GATE_FASTER_SETTLERS_Cos', 'Amount', '1');
--巨像--
--购买商人减30%
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_COLOSSUS', 'COLOSSUS_TRADER_DISCOUNT_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('COLOSSUS_TRADER_DISCOUNT_Cos', 'MODIFIER_PLAYER_CITIES_ADJUST_UNIT_PURCHASE_COST', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('COLOSSUS_TRADER_DISCOUNT_Cos', 'UnitType', 'UNIT_TRADER'),
('COLOSSUS_TRADER_DISCOUNT_Cos', 'Amount', '30');
--空花--
--有粮仓的城市淡水+1粮
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_HANGING_GARDENS', 'HANGING_GARDENS_FRESH_FOOD_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('HANGING_GARDENS_FRESH_FOOD_Cos', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', 'BUILDING_IS_GRANARY_Cos'),
('HANGING_GARDENS_FRESH_FOOD_MODIFIER_Cos', 'MODIFIER_CITY_PLOT_YIELDS_ADJUST_PLOT_YIELD', 'PLOT_IS_FRESH');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('HANGING_GARDENS_FRESH_FOOD_Cos', 'ModifierId', 'HANGING_GARDENS_FRESH_FOOD_MODIFIER_Cos'),
('HANGING_GARDENS_FRESH_FOOD_MODIFIER_Cos', 'YieldType', 'YIELD_FOOD'),
('HANGING_GARDENS_FRESH_FOOD_MODIFIER_Cos', 'Amount', '1');
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId) VALUES
('BUILDING_IS_GRANARY_Cos' , 'REQUIRES_CITY_HAS_GRANARY_Cos');
INSERT INTO RequirementSets (RequirementSetId , RequirementSetType) VALUES
('BUILDING_IS_GRANARY_Cos' , 'REQUIREMENTSET_TEST_ALL');
INSERT INTO Requirements (RequirementId , RequirementType) VALUES
('REQUIRES_CITY_HAS_GRANARY_Cos' , 'REQUIREMENT_CITY_HAS_BUILDING');
INSERT INTO RequirementArguments (RequirementId , Name , Value) VALUES
('REQUIRES_CITY_HAS_GRANARY_Cos' , 'BuildingType' , 'BUILDING_GRANARY');
--鲁尔山谷--
--+6锤，6环辐射
INSERT INTO Building_YieldChanges (BuildingType, YieldType, YieldChange) VALUES
('BUILDING_RUHR_VALLEY', 'YIELD_PRODUCTION', 6);
UPDATE Buildings SET RegionalRange=6 WHERE BuildingType='BUILDING_RUHR_VALLEY';
--本城可以平地矿山
INSERT INTO Types (Type,Kind) VALUES
('MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_VALID_TERRAIN_Cos', 'KIND_MODIFIER');
INSERT INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES
('MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_VALID_TERRAIN_Cos', 'COLLECTION_OWNER', 'EFFECT_ADJUST_IMPROVEMENT_VALID_TERRAIN');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_RUHR_VALLEY', 'RUHR_VALLEY_GRASS_MINE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType) VALUES 
('RUHR_VALLEY_GRASS_MINE_Cos' , 'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_VALID_TERRAIN_Cos');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('RUHR_VALLEY_GRASS_MINE_Cos', 'ImprovementType', 'IMPROVEMENT_MINE'),
('RUHR_VALLEY_GRASS_MINE_Cos', 'TerrainType', 'TERRAIN_GRASS');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_RUHR_VALLEY', 'RUHR_VALLEY_PLAINS_MINE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType) VALUES 
('RUHR_VALLEY_PLAINS_MINE_Cos' , 'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_VALID_TERRAIN_Cos');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('RUHR_VALLEY_PLAINS_MINE_Cos', 'ImprovementType', 'IMPROVEMENT_MINE'),
('RUHR_VALLEY_PLAINS_MINE_Cos', 'TerrainType', 'TERRAIN_PLAINS');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_RUHR_VALLEY', 'RUHR_VALLEY_TUNDRA_MINE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType) VALUES 
('RUHR_VALLEY_TUNDRA_MINE_Cos' , 'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_VALID_TERRAIN_Cos');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('RUHR_VALLEY_TUNDRA_MINE_Cos', 'ImprovementType', 'IMPROVEMENT_MINE'),
('RUHR_VALLEY_TUNDRA_MINE_Cos', 'TerrainType', 'TERRAIN_TUNDRA');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_RUHR_VALLEY', 'RUHR_VALLEY_SNOW_MINE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType) VALUES 
('RUHR_VALLEY_SNOW_MINE_Cos' , 'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_VALID_TERRAIN_Cos');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('RUHR_VALLEY_SNOW_MINE_Cos', 'ImprovementType', 'IMPROVEMENT_MINE'),
('RUHR_VALLEY_SNOW_MINE_Cos', 'TerrainType', 'TERRAIN_SNOW');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_RUHR_VALLEY', 'RUHR_VALLEY_DESERT_MINE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType) VALUES 
('RUHR_VALLEY_DESERT_MINE_Cos' , 'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_VALID_TERRAIN_Cos');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('RUHR_VALLEY_DESERT_MINE_Cos', 'ImprovementType', 'IMPROVEMENT_MINE'),
('RUHR_VALLEY_DESERT_MINE_Cos', 'TerrainType', 'TERRAIN_DESERT');
--马拉卡纳--
--不必平地
DELETE FROM Building_ValidTerrains WHERE BuildingType='BUILDING_ESTADIO_DO_MARACANA';
--马丘比丘--
--人口上山
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_MACHU_PICCHU', 'TRAIT_WORK_GRASS_MOUNTAIN'),
('BUILDING_MACHU_PICCHU', 'TRAIT_WORK_PLAINS_MOUNTAIN'),
('BUILDING_MACHU_PICCHU', 'TRAIT_WORK_DESERT_MOUNTAIN'),
('BUILDING_MACHU_PICCHU', 'TRAIT_WORK_TUNDRA_MOUNTAIN'),
('BUILDING_MACHU_PICCHU', 'TRAIT_WORK_SNOW_MOUNTAIN');
--山脉+1粮
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_MACHU_PICCHU', 'MACHU_PICCHU_MOUNTAIN_FOOD_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('MACHU_PICCHU_MOUNTAIN_FOOD_Cos', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'REQUIREMENTS_PLOT_IS_MOUNTAIN');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('MACHU_PICCHU_MOUNTAIN_FOOD_Cos', 'YieldType', 'YIELD_FOOD'),
('MACHU_PICCHU_MOUNTAIN_FOOD_Cos', 'Amount', '1');
--上师庙--
--相邻上师所有单位加速加力
UPDATE TypeTags SET Tag='CLASS_ALL_UNITS' WHERE Type='ABILITY_GURU_STRENGTH';
UPDATE TypeTags SET Tag='CLASS_ALL_UNITS' WHERE Type='ABILITY_GURU_MOVEMENT';
--摩索拉斯--
--+1大工点
INSERT INTO Building_GreatPersonPoints (BuildingType, GreatPersonClassType, PointsPerTurn) VALUES
('BUILDING_HALICARNASSUS_MAUSOLEUM', 'GREAT_PERSON_CLASS_ENGINEER', 1);
--湖泊也加
UPDATE Modifiers SET SubjectRequirementSetId='PLOT_HAS_COAST_REQUIREMENTS' WHERE ModifierId='HALICARNASSUS_MAUSOLEUM_YIELD_MODIFIER';
--莫斯科剧院--
--本城消耗伟人扩地三格
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_BOLSHOI_THEATRE', 'BOLSHOI_THEATRE_EXPENDED_GREAT_PERSON_TILES_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('BOLSHOI_THEATRE_EXPENDED_GREAT_PERSON_TILES_Cos', 'MODIFIER_PLAYER_CITIES_ADD_EXPENDED_GREAT_PERSON_TILES', 'CITY_HAS_BOLSHOI_THEATRE_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('BOLSHOI_THEATRE_EXPENDED_GREAT_PERSON_TILES_Cos', 'Amount', '3');
INSERT INTO RequirementSets (RequirementSetId , RequirementSetType) VALUES
('CITY_HAS_BOLSHOI_THEATRE_REQUIREMENTS' , 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId) VALUES
('CITY_HAS_BOLSHOI_THEATRE_REQUIREMENTS' , 'REQUIRES_CITY_HAS_BOLSHOI_THEATRE_Cos');
INSERT INTO Requirements (RequirementId , RequirementType) VALUES
('REQUIRES_CITY_HAS_BOLSHOI_THEATRE_Cos' , 'REQUIREMENT_CITY_HAS_BUILDING');
INSERT INTO RequirementArguments (RequirementId , Name , Value) VALUES
('REQUIRES_CITY_HAS_BOLSHOI_THEATRE_Cos' , 'BuildingType' , 'BUILDING_BOLSHOI_THEATRE');
--牛津大学--
--任何平地都可造
INSERT INTO Building_ValidTerrains (BuildingType, TerrainType) VALUES
('BUILDING_OXFORD_UNIVERSITY', 'TERRAIN_TUNDRA'),
('BUILDING_OXFORD_UNIVERSITY', 'TERRAIN_SNOW'),
('BUILDING_OXFORD_UNIVERSITY', 'TERRAIN_DESERT');
--佩特拉--
--基础+2粮2金1锤
INSERT INTO Building_YieldChanges (BuildingType, YieldType, YieldChange) VALUES
('BUILDING_PETRA', 'YIELD_GOLD', 2),
('BUILDING_PETRA', 'YIELD_FOOD', 2),
('BUILDING_PETRA', 'YIELD_PRODUCTION', 1);
--包括山脉和沙泛
UPDATE RequirementSets SET RequirementSetType='REQUIREMENTSET_TEST_ANY' WHERE RequirementSetId='PETRA_YIELD_MODIFIER_REQUIREMENTS';
DELETE FROM RequirementSetRequirements WHERE RequirementSetId='PETRA_YIELD_MODIFIER_REQUIREMENTS' AND RequirementId='REQUIRES_PLOT_HAS_NO_FLOODPLAINS';
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId) VALUES
('PETRA_YIELD_MODIFIER_REQUIREMENTS' , 'PLOT_IS_DESERT_MOUNTAIN_Cos');
INSERT INTO Requirements (RequirementId , RequirementType) VALUES
('PLOT_IS_DESERT_MOUNTAIN_Cos' , 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId , Name , Value) VALUES
('PLOT_IS_DESERT_MOUNTAIN_Cos' , 'TerrainType' , 'TERRAIN_DESERT_MOUNTAIN');
--奇琴伊察--
--基础+2锤2文
INSERT INTO Building_YieldChanges (BuildingType, YieldType, YieldChange) VALUES
('BUILDING_CHICHEN_ITZA', 'YIELD_CULTURE', 2),
('BUILDING_CHICHEN_ITZA', 'YIELD_PRODUCTION', 2);
--全境雨林加1文
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_CHICHEN_ITZA', 'CHICHEN_ITZA_JUNGLE_CULTURE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('CHICHEN_ITZA_JUNGLE_CULTURE_Cos', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'PLOT_HAS_JUNGLE_REQUIREMENTS');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('CHICHEN_ITZA_JUNGLE_CULTURE_Cos', 'YieldType', 'YIELD_CULTURE'),
('CHICHEN_ITZA_JUNGLE_CULTURE_Cos', 'Amount', '1');
--本城雨林额外+1锤1文
UPDATE ModifierArguments SET Value='1' WHERE ModifierId='CHICHEN_ITZA_JUNGLE_CULTURE_MODIFIER' AND Name='Amount';
--桑科雷--
--商路+1科
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_UNIVERSITY_SANKORE', 'SANKORE_DOMESTIC_SCIENCE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('SANKORE_DOMESTIC_SCIENCE_Cos', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_DOMESTIC', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('SANKORE_DOMESTIC_SCIENCE_Cos', 'YieldType', 'YIELD_SCIENCE'),
('SANKORE_DOMESTIC_SCIENCE_Cos', 'Amount', '1');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_UNIVERSITY_SANKORE', 'SANKORE_INTERNATIONAL_SCIENCE_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('SANKORE_INTERNATIONAL_SCIENCE_Cos', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_FOR_INTERNATIONAL', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('SANKORE_INTERNATIONAL_SCIENCE_Cos', 'YieldType', 'YIELD_SCIENCE'),
('SANKORE_INTERNATIONAL_SCIENCE_Cos', 'Amount', '1');
--神谕--
--剧院给大艺大音
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_ORACLE', 'ORACLE_GREATARTISTPOINTS_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('ORACLE_GREATARTISTPOINTS_Cos', 'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 'DISTRICT_IS_THEATER');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('ORACLE_GREATARTISTPOINTS_Cos', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_ARTIST'),
('ORACLE_GREATARTISTPOINTS_Cos', 'Amount', '2');
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_ORACLE', 'ORACLE_GREATMUSICIANPOINTS_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('ORACLE_GREATMUSICIANPOINTS_Cos', 'MODIFIER_SINGLE_CITY_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 'DISTRICT_IS_THEATER');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('ORACLE_GREATMUSICIANPOINTS_Cos', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MUSICIAN'),
('ORACLE_GREATMUSICIANPOINTS_Cos', 'Amount', '2');
--生物圈--
--+300%电
UPDATE ModifierArguments SET Value='300' WHERE ModifierId='BIOSPHERE_MODIFIED_FREE_POWER' AND Name='Amount';
--每有一种地貌和自然奇观城市+3%科技
INSERT INTO BuildingModifiers (BuildingType, ModifierId) SELECT
'BUILDING_BIOSPHERE', 'BIOSPHERE_' || FeatureType || '_SCIENCE_Cos' FROM
Features WHERE FeatureType NOT IN ('FEATURE_BURNING_FOREST', 'FEATURE_BURNT_FOREST', 'FEATURE_BURNING_JUNGLE', 'FEATURE_BURNT_JUNGLE');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) SELECT
'BIOSPHERE_' || FeatureType || '_SCIENCE_Cos', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', 'CITY_HAS_' || FeatureType || '_Cos'FROM
Features WHERE FeatureType NOT IN ('FEATURE_BURNING_FOREST', 'FEATURE_BURNT_FOREST', 'FEATURE_BURNING_JUNGLE', 'FEATURE_BURNT_JUNGLE');
INSERT INTO ModifierArguments (ModifierId , Name , Value) SELECT
'BIOSPHERE_' || FeatureType || '_SCIENCE_Cos', 'YieldType', 'YIELD_SCIENCE' FROM
Features WHERE FeatureType NOT IN ('FEATURE_BURNING_FOREST', 'FEATURE_BURNT_FOREST', 'FEATURE_BURNING_JUNGLE', 'FEATURE_BURNT_JUNGLE');
INSERT INTO ModifierArguments (ModifierId , Name , Value) SELECT
'BIOSPHERE_' || FeatureType || '_SCIENCE_Cos', 'Amount', '3' FROM
Features WHERE FeatureType NOT IN ('FEATURE_BURNING_FOREST', 'FEATURE_BURNT_FOREST', 'FEATURE_BURNING_JUNGLE', 'FEATURE_BURNT_JUNGLE');
INSERT INTO RequirementSets (RequirementSetId , RequirementSetType) SELECT
'CITY_HAS_' || FeatureType || '_Cos', 'REQUIREMENTSET_TEST_ALL' FROM
Features WHERE FeatureType NOT IN ('FEATURE_BURNING_FOREST', 'FEATURE_BURNT_FOREST', 'FEATURE_BURNING_JUNGLE', 'FEATURE_BURNT_JUNGLE');
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId) SELECT
'CITY_HAS_' || FeatureType || '_Cos', 'REQUIRES_' || FeatureType || '_IN_CITY_Cos' FROM
Features WHERE FeatureType NOT IN ('FEATURE_BURNING_FOREST', 'FEATURE_BURNT_FOREST', 'FEATURE_BURNING_JUNGLE', 'FEATURE_BURNT_JUNGLE');
INSERT INTO Requirements (RequirementId , RequirementType) SELECT
'REQUIRES_' || FeatureType || '_IN_CITY_Cos', 'REQUIREMENT_CITY_HAS_FEATURE' FROM
Features WHERE FeatureType NOT IN ('FEATURE_BURNING_FOREST', 'FEATURE_BURNT_FOREST', 'FEATURE_BURNING_JUNGLE', 'FEATURE_BURNT_JUNGLE');
INSERT INTO RequirementArguments (RequirementId, Name, Value) SELECT
'REQUIRES_' || FeatureType || '_IN_CITY_Cos', 'FeatureType', FeatureType FROM
Features WHERE FeatureType NOT IN ('FEATURE_BURNING_FOREST', 'FEATURE_BURNT_FOREST', 'FEATURE_BURNING_JUNGLE', 'FEATURE_BURNT_JUNGLE');
--圣米歇尔山--
--传教士使徒无视控制区
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_MONT_ST_MICHEL', 'MONT_ST_MICHEL_IGNORE_ZOC_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType, Permanent) VALUES
('MONT_ST_MICHEL_IGNORE_ZOC_Cos' , 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 1);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MONT_ST_MICHEL_IGNORE_ZOC_Cos' , 'AbilityType', 'ABILITY_IGNORE_ZOC_ST_MICHEL_Cos');
INSERT INTO Types (Type, Kind) VALUES
('ABILITY_IGNORE_ZOC_ST_MICHEL_Cos', 'KIND_ABILITY');
INSERT INTO TypeTags (Type, Tag) VALUES
('ABILITY_IGNORE_ZOC_ST_MICHEL_Cos', 'CLASS_RELIGIOUS');
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
('ABILITY_IGNORE_ZOC_ST_MICHEL_Cos','IGNOREZOC_IGNORE_ZOC');
INSERT INTO UnitAbilities (UnitAbilityType, Name ,Description ,Inactive) VALUES
('ABILITY_IGNORE_ZOC_ST_MICHEL_Cos', 'LOC_ABILITY_IGNORE_ZOC_ST_MICHEL_NAME_Cos','LOC_ABILITY_IGNORE_ZOC_ST_MICHEL_DESCRIPTION_Cos',1);
--建成后送一个遗物
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_MONT_ST_MICHEL', 'MONT_ST_MICHEL_RELIC_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce , Permanent) VALUES
('MONT_ST_MICHEL_RELIC_Cos' , 'MODIFIER_PLAYER_GRANT_RELIC', 1, 1);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('MONT_ST_MICHEL_RELIC_Cos' , 'Amount', '1');
--不给信仰值
UPDATE Building_YieldChanges SET YieldChange=0 WHERE BuildingType='BUILDING_MONT_ST_MICHEL';
--圣索菲亚--
--非自己建立城市使所有城市+5%信仰
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_HAGIA_SOPHIA', 'HAGIA_SOPHIA_FAITH_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('HAGIA_SOPHIA_FAITH_Cos', 'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER', 'CITY_NOT_FOUNDED'),
('HAGIA_SOPHIA_FAITH_MODIFIER_Cos', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_YIELD_MODIFIER', NULL);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('HAGIA_SOPHIA_FAITH_Cos', 'ModifierId', 'HAGIA_SOPHIA_FAITH_MODIFIER_Cos'),
('HAGIA_SOPHIA_FAITH_MODIFIER_Cos', 'YieldType', 'YIELD_FAITH'),
('HAGIA_SOPHIA_FAITH_MODIFIER_Cos', 'Amount', '5');
--圣瓦西里--
--冻土+1信仰
UPDATE ModifierArguments SET Value='YIELD_FOOD,YIELD_FAITH' WHERE ModifierId='STBASILS_ADDFOOD_MODIFIER' AND Name='YieldType';
UPDATE ModifierArguments SET Value='1,1' WHERE ModifierId='STBASILS_ADDFOOD_MODIFIER' AND Name='Amount';
--冻土山脉也加
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId) VALUES
('PLOT_HAS_ANYTUNDRA_REQUIREMENTS' , 'PLOT_IS_TUNDRA_MOUNTAIN_Cos');
INSERT INTO Requirements (RequirementId , RequirementType) VALUES
('PLOT_IS_TUNDRA_MOUNTAIN_Cos' , 'REQUIREMENT_PLOT_TERRAIN_TYPE_MATCHES');
INSERT INTO RequirementArguments (RequirementId , Name , Value) VALUES
('PLOT_IS_TUNDRA_MOUNTAIN_Cos' , 'TerrainType' , 'TERRAIN_TUNDRA_MOUNTAIN');
--威尼斯军械库--
--海军+1射程
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_VENETIAN_ARSENAL', 'VENETIAN_ARSENAL_BONUS_RANGE_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType, Permanent) VALUES
('VENETIAN_ARSENAL_BONUS_RANGE_Cos' , 'MODIFIER_PLAYER_UNITS_GRANT_ABILITY', 1);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('VENETIAN_ARSENAL_BONUS_RANGE_Cos' , 'AbilityType', 'ABILITY_BONUS_RANGE_VENETIAN_ARSENAL_Cos');
INSERT INTO Types (Type, Kind) VALUES
('ABILITY_BONUS_RANGE_VENETIAN_ARSENAL_Cos', 'KIND_ABILITY');
INSERT INTO TypeTags (Type, Tag) VALUES
('ABILITY_BONUS_RANGE_VENETIAN_ARSENAL_Cos', 'CLASS_NAVAL_RANGED');
INSERT INTO UnitAbilityModifiers (UnitAbilityType, ModifierId) VALUES
('ABILITY_BONUS_RANGE_VENETIAN_ARSENAL_Cos','FORWARD_OBSERVERS_BONUS_RANGE');
INSERT INTO UnitAbilities (UnitAbilityType, Name ,Description ,Inactive) VALUES
('ABILITY_BONUS_RANGE_VENETIAN_ARSENAL_Cos', 'LOC_ABILITY_BONUS_RANGE_VENETIAN_ARSENAL_NAME_Cos','LOC_ABILITY_BONUS_RANGE_VENETIAN_ARSENAL_DESCRIPTION_Cos',1);
--吴哥窟--
--所有城市+1初始人口
UPDATE Modifiers SET RunOnce=0 WHERE ModifierId='ANGKORWAT_ADDPOPULATION';
--西印度--
--+20%金币
UPDATE ModifierArguments SET Value='20' WHERE ModifierId='CONTRATACION_FOREIGNGOLD' AND Name='Amount';
--悉尼歌剧院--
--港口相邻文化
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_SYDNEY_OPERA_HOUSE', 'SYDNEY_OPERA_HOUSE_HARBOR_CULTURE_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES 	
('SYDNEY_OPERA_HOUSE_HARBOR_CULTURE_Cos', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_YIELD_BASED_ON_ADJACENCY_BONUS', 'DISTRICT_IS_HARBOR');
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('SYDNEY_OPERA_HOUSE_HARBOR_CULTURE_Cos', 'YieldTypeToMirror', 'YIELD_GOLD'),
('SYDNEY_OPERA_HOUSE_HARBOR_CULTURE_Cos', 'YieldTypeToGrant', 'YIELD_CULTURE');
--议会大厦--
--送3使者
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_ORSZAGHAZ', 'ORSZAGHAZ_INFLUENCE_TOKEN_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce , Permanent) VALUES
('ORSZAGHAZ_INFLUENCE_TOKEN_Cos' , 'MODIFIER_PLAYER_GRANT_INFLUENCE_TOKEN', 1, 1);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES
('ORSZAGHAZ_INFLUENCE_TOKEN_Cos' , 'Amount', '3');
--休伊神庙--
--基础+2粮1锤
INSERT INTO Building_YieldChanges (BuildingType, YieldType, YieldChange) VALUES
('BUILDING_HUEY_TEOCALLI', 'YIELD_FOOD', 2),
('BUILDING_HUEY_TEOCALLI', 'YIELD_PRODUCTION', 1);
--相邻湖也加
UPDATE RequirementSets SET RequirementSetType='REQUIREMENTSET_TEST_ANY' WHERE RequirementSetId='FOODHUEY_PLOT_IS_LAKE_REQUIREMENTS';
UPDATE Modifiers SET SubjectRequirementSetId='FOODHUEY_PLOT_IS_LAKE_REQUIREMENTS' WHERE ModifierId='HUEY_LAKE_PRODUCTION_MODIFIER';
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId) VALUES
('FOODHUEY_PLOT_IS_LAKE_REQUIREMENTS' , 'REQUIRES_PLOT_ADJACENT_TO_LAKE');
--宙斯像
--抗骑兵+1速
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_STATUE_OF_ZEUS', 'STATUE_OF_ZEUS_ANTI_CAVALRY_MOVEMENT_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('STATUE_OF_ZEUS_ANTI_CAVALRY_MOVEMENT_Cos', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT', 'UNIT_IS_ANTI_CAVALRY_Cos');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('STATUE_OF_ZEUS_ANTI_CAVALRY_MOVEMENT_Cos', 'Amount', '1');
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId) VALUES
('UNIT_IS_ANTI_CAVALRY_Cos' , 'REQUIRES_UNIT_IS_ANTI_CAVALRY_Cos');
INSERT INTO RequirementSets (RequirementSetId , RequirementSetType) VALUES
('UNIT_IS_ANTI_CAVALRY_Cos' , 'REQUIREMENTSET_TEST_ALL');
INSERT INTO Requirements (RequirementId , RequirementType) VALUES
('REQUIRES_UNIT_IS_ANTI_CAVALRY_Cos' , 'REQUIREMENT_UNIT_PROMOTION_CLASS_MATCHES');
INSERT INTO RequirementArguments (RequirementId , Name , Value) VALUES
('REQUIRES_UNIT_IS_ANTI_CAVALRY_Cos' , 'UnitPromotionClass' , 'PROMOTION_CLASS_ANTI_CAVALRY');
--自由女神像--
--送2开拓者
INSERT INTO BuildingModifiers (BuildingType, ModifierId) VALUES
('BUILDING_STATUE_LIBERTY', 'STATUE_LIBERTY_SETTLER_Cos');
INSERT INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent) VALUES
('STATUE_LIBERTY_SETTLER_Cos', 'MODIFIER_SINGLE_CITY_GRANT_UNIT_IN_CITY', 1, 1);
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('STATUE_LIBERTY_SETTLER_Cos', 'UnitType', 'UNIT_SETTLER'),
('STATUE_LIBERTY_SETTLER_Cos', 'Amount', '2');
