--蒙古
--牧场为商业中心提供大量加成
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
    ('TRAIT_CIVILIZATION_MONGOLIAN_ORTOO', 'COMMERCIAL_HUB_ADJACENCY_PASTURE_CosMongolia');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES 	
    ('COMMERCIAL_HUB_ADJACENCY_PASTURE_CosMongolia', 'MODIFIER_PLAYER_CITIES_IMPROVEMENT_ADJACENCY', NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
	('COMMERCIAL_HUB_ADJACENCY_PASTURE_CosMongolia',			'Amount',					2),
	('COMMERCIAL_HUB_ADJACENCY_PASTURE_CosMongolia', 'Description', 'LOC_DISTRICT_PASTURE_GOLD_CosMongolia'),
	('COMMERCIAL_HUB_ADJACENCY_PASTURE_CosMongolia',			'DistrictType',				'DISTRICT_COMMERCIAL_HUB'),
	('COMMERCIAL_HUB_ADJACENCY_PASTURE_CosMongolia',			'ImprovementType',			'IMPROVEMENT_PASTURE'),
	('COMMERCIAL_HUB_ADJACENCY_PASTURE_CosMongolia',			'TilesRequired',			1),
	('COMMERCIAL_HUB_ADJACENCY_PASTURE_CosMongolia',			'YieldType',				'YIELD_GOLD');
--经过国内贸易站+1金币
--MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_POST_IN_OWN_CITY
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
    ('TRAIT_CIVILIZATION_MONGOLIAN_ORTOO', 'TRAIT_GOLD_FROM_DOMESTIC_TRADING_POSTS');
--经过国外贸易站+1金币
--MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_POST_IN_FOREIGN_CITY
INSERT INTO TraitModifiers (TraitType, ModifierId) VALUES 
    ('TRAIT_CIVILIZATION_MONGOLIAN_ORTOO', 'ORTOO_TRADING_POST_BONUS');
INSERT INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES
('ORTOO_TRADING_POST_BONUS', 'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_POST_IN_FOREIGN_CITY', NULL);
INSERT INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('ORTOO_TRADING_POST_BONUS', 'Amount', 1),
('ORTOO_TRADING_POST_BONUS', 'YieldType', 'YIELD_GOLD');
--成吉思汗--
--骑兵可以抓所有战斗单位
UPDATE Modifiers SET SubjectRequirementSetId='ATTACKER_OPPONENT_IS_LAND_UNIT_REQUIREMENTS_CosMongolia' WHERE SubjectRequirementSetId='ATTACKER_OPPONENT_IS_CAVALRY_UNIT_REQUIREMENTS';
INSERT INTO RequirementSets (RequirementSetId , RequirementSetType)
	VALUES ('ATTACKER_OPPONENT_IS_LAND_UNIT_REQUIREMENTS_CosMongolia' , 'REQUIREMENTSET_TEST_ALL');
INSERT INTO RequirementSetRequirements (RequirementSetId , RequirementId)
	VALUES ('ATTACKER_OPPONENT_IS_LAND_UNIT_REQUIREMENTS_CosMongolia' , 'OPPONENT_IS_LAND_UNIT_REQUIREMENTS');
--斡耳朵
--攻城+1速
INSERT INTO TypeTags (Type, Tag)
	VALUES ('ABILITY_ORDU_INCREASED_MOVEMENT', 'CLASS_SIEGE');
--一级关联马
UPDATE StartBiasResources SET Tier=1 WHERE CivilizationType='CIVILIZATION_MONGOLIA' AND ResourceType='RESOURCE_HORSES';
INSERT INTO StartBiasResources (CivilizationType, ResourceType, Tier) VALUES
('CIVILIZATION_MONGOLIA', 'RESOURCE_CATTLE', 3),
('CIVILIZATION_MONGOLIA', 'RESOURCE_SHEEP', 3);