--土木工程--
--人口上山
INSERT INTO CivicModifiers (CivicType, ModifierId) VALUES
('CIVIC_CIVIL_ENGINEERING', 'TRAIT_WORK_GRASS_MOUNTAIN'),
('CIVIC_CIVIL_ENGINEERING', 'TRAIT_WORK_PLAINS_MOUNTAIN'),
('CIVIC_CIVIL_ENGINEERING', 'TRAIT_WORK_DESERT_MOUNTAIN'),
('CIVIC_CIVIL_ENGINEERING', 'TRAIT_WORK_TUNDRA_MOUNTAIN'),
('CIVIC_CIVIL_ENGINEERING', 'TRAIT_WORK_SNOW_MOUNTAIN');
--山+2锤
INSERT INTO CivicModifiers (CivicType, ModifierId) VALUES
('CIVIC_CIVIL_ENGINEERING', 'CIVIL_ENGINEERING_MOUNTAIN_PRODUCTION_Cos');
INSERT INTO Modifiers (ModifierId , ModifierType ,SubjectRequirementSetId) VALUES
('CIVIL_ENGINEERING_MOUNTAIN_PRODUCTION_Cos', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 'REQUIREMENTS_PLOT_IS_MOUNTAIN');
INSERT INTO ModifierArguments (ModifierId , Name , Value) VALUES
('CIVIL_ENGINEERING_MOUNTAIN_PRODUCTION_Cos', 'YieldType', 'YIELD_PRODUCTION'),
('CIVIL_ENGINEERING_MOUNTAIN_PRODUCTION_Cos', 'Amount', '2');

--封建主义--
--5块田
UPDATE Boosts SET NumItems=5 Where CivicType='CIVIC_FEUDALISM';

--近未来统治--
--+1通配槽


--未来市政--
--+1影响力点数

--