--转换燃煤--
UPDATE Projects SET Cost=150 WHERE ProjectType='PROJECT_CONVERT_REACTOR_TO_COAL';
--转换燃油--
--精炼解锁
UPDATE Projects SET Cost=180, PrereqTech='TECH_REFINING' WHERE ProjectType='PROJECT_CONVERT_REACTOR_TO_OIL';
--转换核电--
UPDATE Projects SET Cost=240 WHERE ProjectType='PROJECT_CONVERT_REACTOR_TO_URANIUM';
--关煤电--
UPDATE Projects SET Cost=150 WHERE ProjectType='PROJECT_DECOMMISSION_COAL_POWER_PLANT';
--关油电--
UPDATE Projects SET Cost=150 WHERE ProjectType='PROJECT_DECOMMISSION_OIL_POWER_PLANT';
--关核电--
UPDATE Projects SET Cost=150 WHERE ProjectType='PROJECT_DECOMMISSION_NUCLEAR_POWER_PLANT';
