--法西斯
DELETE FROM TypeTags WHERE Type='ABILITY_FASCISM_ATTACK_BUFF';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_FASCISM_ATTACK_BUFF','CLASS_ALL_COMBAT_UNITS');
--共产
DELETE FROM TypeTags WHERE Type='ABILITY_COMMUNISM_DEFENSE_BUFF';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_COMMUNISM_DEFENSE_BUFF','CLASS_ALL_COMBAT_UNITS');
--菲利普
DELETE FROM TypeTags WHERE Type='ABILITY_PHILIP_II_COMBAT_BONUS_OTHER_RELIGION';
INSERT INTO TypeTags (Type, Tag) VALUES
('ABILITY_PHILIP_II_COMBAT_BONUS_OTHER_RELIGION','CLASS_ALL_COMBAT_UNITS'),
('ABILITY_PHILIP_II_COMBAT_BONUS_OTHER_RELIGION','CLASS_RELIGIOUS_ALL');
--砍二
DELETE FROM TypeTags WHERE Type='ABILITY_MONTEZUMA_COMBAT_BONUS_PER_LUXURY';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_MONTEZUMA_COMBAT_BONUS_PER_LUXURY','CLASS_ALL_COMBAT_UNITS');
--巴巴罗萨
DELETE FROM TypeTags WHERE Type='ABILITY_BARBAROSSA_COMBAT_BONUS_VS_CITY_STATES';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_BARBAROSSA_COMBAT_BONUS_VS_CITY_STATES','CLASS_ALL_COMBAT_UNITS');
--武美
DELETE FROM TypeTags WHERE Type='ABILITY_ROOSEVELT_COMBAT_BONUS_HOME_CONTINENT';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_ROOSEVELT_COMBAT_BONUS_HOME_CONTINENT','CLASS_ALL_COMBAT_UNITS');
--托米丽司加力
DELETE FROM TypeTags WHERE Type='ABILITY_TOMYRIS_BONUS_VS_WOUNDED_UNITS';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_TOMYRIS_BONUS_VS_WOUNDED_UNITS','CLASS_ALL_COMBAT_UNITS');
--托米丽司回血
DELETE FROM TypeTags WHERE Type='ABILITY_TOMYRIS_HEAL_AFTER_DEFEATING_UNIT';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_TOMYRIS_HEAL_AFTER_DEFEATING_UNIT','CLASS_ALL_COMBAT_UNITS');
--女希腊
DELETE FROM TypeTags WHERE Type='ABILITY_GORGO_POLICY_SLOT_COMBAT_BONUS';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_GORGO_POLICY_SLOT_COMBAT_BONUS','CLASS_ALL_COMBAT_UNITS');
--法西斯传承
DELETE FROM TypeTags WHERE Type='ABILITY_FASCISM_LEGACY_ATTACK_BUFF';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_FASCISM_LEGACY_ATTACK_BUFF','CLASS_ALL_COMBAT_UNITS');
--马普切经验
DELETE FROM TypeTags WHERE Type='ABILITY_TOQUI_XP_FROM_GOVERNOR';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_TOQUI_XP_FROM_GOVERNOR','CLASS_ALL_COMBAT_UNITS');
DELETE FROM TypeTags WHERE Type='ABILITY_TOQUI_XP_FROM_GOVERNOR_NOT_FOUNDED';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_TOQUI_XP_FROM_GOVERNOR_NOT_FOUNDED','CLASS_ALL_COMBAT_UNITS');
--马普切加力
DELETE FROM TypeTags WHERE Type='ABILITY_TOQUI_COMBAT_BUFF_VS_GOLDEN_AGE';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_TOQUI_COMBAT_BUFF_VS_GOLDEN_AGE','CLASS_ALL_COMBAT_UNITS');
--光荣时刻
DELETE FROM TypeTags WHERE Type='ABILITY_FINEST_HOUR_FRIENDLY_TERRITORY';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_FINEST_HOUR_FRIENDLY_TERRITORY','CLASS_ALL_COMBAT_UNITS');
--数字化民主
DELETE FROM TypeTags WHERE Type='ABILITY_DIGITAL_DEMOCRACY_DEBUFF';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_DIGITAL_DEMOCRACY_DEBUFF','CLASS_ALL_COMBAT_UNITS');
--全球联合
DELETE FROM TypeTags WHERE Type='ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_GLOBAL_COALITION_FRIENDLY_TERRITORY','CLASS_ALL_COMBAT_UNITS');
--网络战
DELETE FROM TypeTags WHERE Type='ABILITY_CYBER_WARFARE_COMBAT_BONUS';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_CYBER_WARFARE_COMBAT_BONUS','CLASS_ALL_COMBAT_UNITS');
--渡鸦之王
DELETE FROM TypeTags WHERE Type='ABILITY_THE_RAVEN_KING';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_THE_RAVEN_KING','CLASS_ALL_COMBAT_UNITS');
--玛雅
DELETE FROM TypeTags WHERE Type='ABILITY_MUTAL_COMBAT_STRENGTH_NEAR_CAPITAL';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_MUTAL_COMBAT_STRENGTH_NEAR_CAPITAL','CLASS_ALL_COMBAT_UNITS');
--拜占庭
DELETE FROM TypeTags WHERE Type='ABILITY_BYZANTIUM_COMBAT_UNITS';
INSERT INTO TypeTags (Type, Tag) VALUES ('ABILITY_BYZANTIUM_COMBAT_UNITS','CLASS_ALL_COMBAT_UNITS');
--大灯塔水运
DELETE FROM TypeTags WHERE Type='ABILITY_GREAT_LIGHTHOUSE_EMBARKED_MOVEMENT';
INSERT INTO TypeTags (Type, Tag) VALUES
('ABILITY_GREAT_LIGHTHOUSE_EMBARKED_MOVEMENT','CLASS_ALL_COMBAT_UNITS'),
('ABILITY_GREAT_LIGHTHOUSE_EMBARKED_MOVEMENT','CLASS_LANDCIVILIAN'),
('ABILITY_GREAT_LIGHTHOUSE_EMBARKED_MOVEMENT','CLASS_SUPPORT');
--毛利水运
DELETE FROM TypeTags WHERE Type='ABILITY_MANA';
INSERT INTO TypeTags (Type, Tag) VALUES
('ABILITY_MANA','CLASS_ALL_COMBAT_UNITS'),
('ABILITY_MANA','CLASS_LANDCIVILIAN'),
('ABILITY_MANA','CLASS_SUPPORT');
--赵夫人
DELETE FROM TypeTags WHERE Type='ABILITY_TRIEU_FEATURES';
INSERT INTO TypeTags (Type, Tag) VALUES
('ABILITY_TRIEU_FEATURES','CLASS_ALL_COMBAT_UNITS'),
('ABILITY_TRIEU_FEATURES','CLASS_LANDCIVILIAN'),
('ABILITY_TRIEU_FEATURES','CLASS_SUPPORT');
--远程单位
INSERT INTO TypeTags (Type, Tag) VALUES
('UNIT_SKIRMISHER','CLASS_RANGED'), --散兵
('UNIT_SPEC_OPS','CLASS_RANGED'),
('UNIT_SPEC_OPS','CLASS_MOBILE_RANGED'), --特种部队
('UNIT_MONGOLIAN_KESHIG','CLASS_MOBILE_RANGED'),
('UNIT_MONGOLIAN_KESHIG','CLASS_RANGED'); --怯薛歹
INSERT INTO TypeTags (Type, Tag) VALUES
('ABILITY_HOJO_TOKIMUNE_COASTAL_COMBAT_BONUS','CLASS_WARRIOR_MONK'),
('ABILITY_HOJO_TOKIMUNE_COASTAL_COMBAT_BONUS','CLASS_LIGHT_CHARIOT'),
('ABILITY_HOJO_TOKIMUNE_COASTAL_COMBAT_BONUS','CLASS_HEAVY_CHARIOT'),
('ABILITY_HOJO_TOKIMUNE_COASTAL_COMBAT_BONUS','CLASS_RANGED_CAVALRY'),
('ABILITY_HOJO_TOKIMUNE_COASTAL_COMBAT_BONUS','CLASS_GIANT_DEATH_ROBOT'),--神风
('ABILITY_ALPINE_TRAINING','CLASS_WARRIOR_MONK'),
('ABILITY_ALPINE_TRAINING','CLASS_LIGHT_CHARIOT'),
('ABILITY_ALPINE_TRAINING','CLASS_HEAVY_CHARIOT'),--高山训练
('ABILITY_TWILIGHT_VALOR_ATTACK_BONUS','CLASS_WARRIOR_MONK'),
('ABILITY_TWILIGHT_VALOR_ATTACK_BONUS','CLASS_HEAVY_CHARIOT'),--迟暮勇武
('ABILITY_WOLIN_NAVAL_UNITS','CLASS_NAVAL_CARRIER'); --沃林

